/*
 * Copyright (c) 2026
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Fixed node_id -> subevent assignment table, covering every physical
 * peripheral across every central rig (see NOTES.md 2026-08-07). Replaces
 * central's old dynamic "first free slot" allocation.
 *
 * GENERATED by tools/gen_node_slot_table.py -- do not hand-edit. Edit the
 * source CSV and regenerate instead, so collision/range checks stay
 * trustworthy (this file's own build-time validation, see
 * node_slot_table_validate() in central/src/main.c, is a second
 * independent check on top of this script -- both should agree).
 *
 * To add/move a node: edit the source CSV, regenerate this file, then
 * rebuild+reflash ONLY the central(s) whose central_id changed (peripherals
 * don't need to know their own subevent -- central still hands it out over
 * the existing GATT write_timing characteristic, just from this table now
 * instead of first-free-slot allocation).
 */

#ifndef NODE_SLOT_TABLE_H_
#define NODE_SLOT_TABLE_H_

struct node_slot_entry {
	uint16_t central_id;
	uint16_t node_id;
	uint8_t subevent;
};

static const struct node_slot_entry node_slot_table[] = {
	{ .central_id = 1, .node_id = 1, .subevent = 0 },
	{ .central_id = 1, .node_id = 2, .subevent = 1 },
	{ .central_id = 1, .node_id = 3, .subevent = 2 },
	{ .central_id = 1, .node_id = 4, .subevent = 3 },
	{ .central_id = 1, .node_id = 5, .subevent = 4 },
	{ .central_id = 1, .node_id = 6, .subevent = 5 },
	{ .central_id = 1, .node_id = 7, .subevent = 6 },
	{ .central_id = 1, .node_id = 8, .subevent = 7 },
	{ .central_id = 1, .node_id = 9, .subevent = 8 },
	{ .central_id = 1, .node_id = 10, .subevent = 9 },
	{ .central_id = 1, .node_id = 11, .subevent = 10 },
	{ .central_id = 1, .node_id = 12, .subevent = 11 },
	{ .central_id = 1, .node_id = 13, .subevent = 12 },
	{ .central_id = 1, .node_id = 14, .subevent = 13 },
	{ .central_id = 1, .node_id = 15, .subevent = 14 },
	{ .central_id = 1, .node_id = 16, .subevent = 15 },
	{ .central_id = 1, .node_id = 24, .subevent = 16 },
};

#endif /* NODE_SLOT_TABLE_H_ */
