#!/usr/bin/env python3
"""Generate central/node_slot_table.h from a plain CSV of (central_id, node_id).

Input CSV format, one row per physical peripheral, no header line:
    central_id,node_id
    1,3
    1,7
    2,31
    2,35
    ...

Subevent numbers are assigned automatically per central_id, in the order
each node_id first appears for that central_id (0, 1, 2, ...) -- not by any
formula on node_id itself, which is the whole point (see node_slot_table.h's
own comment on why a formula like node_id % NUM_SUBEVENTS isn't used).

Refuses to generate a table if:
  - the same (central_id, node_id) pair appears twice in the input
  - any central_id ends up with more node_id entries than NUM_SUBEVENTS
    (see common/pawr_protocol.h -- pass --num-subevents if it's not 20)

Usage:
    python tools/gen_node_slot_table.py nodes.csv > central/node_slot_table.h
    python tools/gen_node_slot_table.py nodes.csv --num-subevents 20 -o central/node_slot_table.h
"""
import argparse
import csv
import sys
from collections import defaultdict

HEADER = """/*
 * Copyright (c) 2026
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Fixed node_id -> subevent assignment table, covering every physical
 * peripheral across every central rig (see NOTES.md 2026-08-07). Replaces
 * central's old dynamic "first free slot" allocation.
 *
 * GENERATED by tools/gen_node_slot_table.py -- do not hand-edit. Edit the
 * source CSV and regenerate instead, so collision/range checks stay
 * trustworthy (this file's own build-time validation, see
 * node_slot_table_validate() in central/src/main.c, is a second
 * independent check on top of this script -- both should agree).
 *
 * To add/move a node: edit the source CSV, regenerate this file, then
 * rebuild+reflash ONLY the central(s) whose central_id changed (peripherals
 * don't need to know their own subevent -- central still hands it out over
 * the existing GATT write_timing characteristic, just from this table now
 * instead of first-free-slot allocation).
 */

#ifndef NODE_SLOT_TABLE_H_
#define NODE_SLOT_TABLE_H_

struct node_slot_entry {
\tuint16_t central_id;
\tuint16_t node_id;
\tuint8_t subevent;
};

static const struct node_slot_entry node_slot_table[] = {
"""

FOOTER = """};

#endif /* NODE_SLOT_TABLE_H_ */
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv_path", help="input CSV: central_id,node_id per line, no header")
    ap.add_argument("--num-subevents", type=int, default=20,
                     help="must match NUM_SUBEVENTS in common/pawr_protocol.h (default 20)")
    ap.add_argument("-o", "--output", help="output path (default: stdout)")
    args = ap.parse_args()

    rows = []
    seen = set()
    with open(args.csv_path, newline="") as f:
        reader = csv.reader(f)
        for lineno, row in enumerate(reader, start=1):
            if not row or row[0].strip().startswith("#"):
                continue
            if len(row) != 2:
                sys.exit(f"{args.csv_path}:{lineno}: expected 'central_id,node_id', got {row!r}")
            try:
                central_id, node_id = int(row[0]), int(row[1])
            except ValueError:
                sys.exit(f"{args.csv_path}:{lineno}: non-integer value in {row!r}")

            key = (central_id, node_id)
            if key in seen:
                sys.exit(f"{args.csv_path}:{lineno}: duplicate entry for central {central_id} node {node_id}")
            seen.add(key)
            rows.append((central_id, node_id))

    if not rows:
        sys.exit(f"{args.csv_path}: no data rows found")

    # Assign subevents per central_id in first-seen order.
    by_central = defaultdict(list)
    for central_id, node_id in rows:
        by_central[central_id].append(node_id)

    for central_id, node_ids in by_central.items():
        if len(node_ids) > args.num_subevents:
            sys.exit(
                f"central {central_id} has {len(node_ids)} nodes but only "
                f"{args.num_subevents} subevents available -- reduce the node "
                f"count for this central, split it across another central, or "
                f"pass --num-subevents if NUM_SUBEVENTS was raised in "
                f"common/pawr_protocol.h"
            )

    lines = []
    for central_id in sorted(by_central):
        for subevent, node_id in enumerate(by_central[central_id]):
            lines.append(
                f"\t{{ .central_id = {central_id}, .node_id = {node_id}, .subevent = {subevent} }},"
            )
        lines.append("")
    # Drop the trailing blank line before the closing brace.
    if lines and lines[-1] == "":
        lines.pop()

    output = HEADER + "\n".join(lines) + "\n" + FOOTER

    if args.output:
        with open(args.output, "w", newline="\n") as f:
            f.write(output)
        total = sum(len(v) for v in by_central.values())
        print(f"Wrote {args.output}: {total} nodes across {len(by_central)} central(s)", file=sys.stderr)
        for central_id in sorted(by_central):
            print(f"  central {central_id}: {len(by_central[central_id])} nodes, "
                  f"subevents 0-{len(by_central[central_id]) - 1}", file=sys.stderr)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
